server:
  port: 8081

#mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring-security-test?characterEncoding=utf8&userSSL=false&&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password:

#thymeleaf

  thymeleaf:
    cache: false

#    springMVC
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
#    prefix: classpath:/templates/
#    suffix: .html
#    mode: HTML5
#    encoding: utf-8
#    servlet:
#      content-type: text/html

# mybatis
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.wlp.security.pojo

#spring security

#  security:
#    user:
#      name: admin
#      password: 888

